### ISSUE TITLE
Password in JSON response

### ISSUE THREAD

**Issue by ceemion** [SundayAdefila/cGuides#27]
Remove password and password_confirmation from response after registration.
@SundayAdefila

**Comment by SundayAdefila** [comment]
PR here: https://github.com/SundayAdefila/cGuides/pull/30

**Comment by ceemion** [comment]
Thanks.

**Comment by SundayAdefila** [comment]
Can we mark this as solved now?

**Comment by ceemion** [comment]
Yup
